#!/bin/sh

# import helpers
source `dirname $0`/helpers

# Install go packages
function install_go_packages {
  if ! type "go" > /dev/null; then
    eerr "Go must be installed first..."; exit 1
  fi

  einf "Installing go packages"
  cat $GO_PACKAGES | xargs go get
}

askdo install_go_packages "Install go packages?"
